"""
Plan Generation Domain Models

Represents plan generation sessions, candidate plans, and selections.
Follows the same pattern as idea generation models.
"""

from datetime import datetime
from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field
from enum import Enum


class PlanSessionStatus(str, Enum):
    """Plan session lifecycle states."""
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


class PaperType(str, Enum):
    """Paper type categories for plan generation."""
    ALGORITHMIC_METHOD = "algorithmic_method"
    SYSTEMS_INFRASTRUCTURE = "systems_infrastructure"
    APPLICATION_DOMAIN = "application_domain"
    SURVEY_TUTORIAL = "survey_tutorial"
    BENCHMARK_DATASET = "benchmark_dataset"
    EVALUATION_METRICS = "evaluation_metrics"
    SECURITY_ROBUSTNESS = "security_robustness"
    THEORY_ANALYSIS = "theory_analysis"
    MULTIMODAL_AGENT = "multimodal_agent"


PAPER_TYPE_LABELS: Dict[str, str] = {
    PaperType.ALGORITHMIC_METHOD: "Algorithmic Method",
    PaperType.SYSTEMS_INFRASTRUCTURE: "Systems / Infrastructure",
    PaperType.APPLICATION_DOMAIN: "Application / Domain",
    PaperType.SURVEY_TUTORIAL: "Survey / Tutorial",
    PaperType.BENCHMARK_DATASET: "Benchmark / Dataset",
    PaperType.EVALUATION_METRICS: "Evaluation / Metrics",
    PaperType.SECURITY_ROBUSTNESS: "Security / Robustness",
    PaperType.THEORY_ANALYSIS: "Theory / Analysis",
    PaperType.MULTIMODAL_AGENT: "Multimodal / Agent",
}


class PlanSessionConfig(BaseModel):
    """Configuration for a plan generation session."""
    providerName: str = Field(default="moonshot")
    model: str = Field(default="moonshot-v1-8k")
    ideaSessionId: Optional[str] = Field(default=None)
    ideaCandidateId: Optional[str] = Field(default=None)
    ideaCandidateTitle: Optional[str] = Field(default=None)
    ideaSeedQuery: Optional[str] = Field(default=None)
    paperType: str = Field(default="algorithmic_method")
    directionId: Optional[str] = Field(default=None)
    directionTitle: Optional[str] = Field(default=None)
    maxCandidates: int = Field(default=3, ge=1, le=10)
    userNotes: Optional[str] = Field(default=None)


class ScoreBreakdown(BaseModel):
    """Detailed score breakdown for a candidate plan."""
    novelty: float = Field(default=0.0, ge=0, le=10)
    feasibility: float = Field(default=0.0, ge=0, le=10)
    impact: float = Field(default=0.0, ge=0, le=10)
    clarity: float = Field(default=0.0, ge=0, le=10)
    risk: float = Field(default=0.0, ge=0, le=10)
    overall: float = Field(default=0.0, ge=0, le=10)
    rationale: str = Field(default="")


class ExperimentDesign(BaseModel):
    """Experiment design details for a candidate plan."""
    research_question: str = Field(default="")
    hypothesis: str = Field(default="")
    variables: Dict[str, Any] = Field(default_factory=dict)
    methodology: Dict[str, Any] = Field(default_factory=dict)
    expected_outcomes: Dict[str, Any] = Field(default_factory=dict)


class CandidatePlan(BaseModel):
    """A single candidate plan generated by LLM."""
    id: str
    sessionId: str
    indexNumber: int = Field(ge=1, description="1-based index")
    title: str = Field(default="")
    planAbstract: str = Field(default="")
    novelty: str = Field(default="")
    feasibility: str = Field(default="")
    risks: str = Field(default="")
    gapAnalysis: str = Field(default="")
    method: str = Field(default="")
    experimentDesign: ExperimentDesign = Field(default_factory=ExperimentDesign)
    evaluationProtocol: Dict[str, Any] = Field(default_factory=dict)
    ablations: List[str] = Field(default_factory=list)
    baselines: List[str] = Field(default_factory=list)
    resourcesEstimate: str = Field(default="")
    scoreBreakdown: ScoreBreakdown = Field(default_factory=ScoreBreakdown)
    overallScore: float = Field(default=0.0, ge=0, le=10)
    createdAt: datetime = Field(default_factory=datetime.utcnow)


class PlanStepResult(BaseModel):
    """Result of a single plan generation step."""
    name: str
    status: str = Field(description="ok | failed | skipped")
    startedAt: Optional[datetime] = None
    endedAt: Optional[datetime] = None
    durationSeconds: float = 0.0
    error: Optional[str] = None


class PlanWorkflowTrace(BaseModel):
    """Trace of the plan generation workflow."""
    sessionId: str
    startedAt: Optional[datetime] = None
    endedAt: Optional[datetime] = None
    totalSteps: int = 0
    successfulSteps: int = 0
    failedSteps: int = 0
    steps: List[PlanStepResult] = Field(default_factory=list)


class PlanSession(BaseModel):
    """Plan generation session."""
    id: str
    config: PlanSessionConfig
    status: PlanSessionStatus = PlanSessionStatus.PENDING
    createdAt: datetime = Field(default_factory=datetime.utcnow)
    startedAt: Optional[datetime] = None
    endedAt: Optional[datetime] = None
    duration: Optional[int] = None
    candidateIds: List[str] = Field(default_factory=list)
    selectedCandidateId: Optional[str] = None
    resultingPlanId: Optional[str] = None
    trace: Optional[PlanWorkflowTrace] = None
    errorMessage: Optional[str] = None

    def is_terminal(self) -> bool:
        return self.status in (
            PlanSessionStatus.COMPLETED,
            PlanSessionStatus.FAILED,
            PlanSessionStatus.CANCELLED,
        )


class SelectedPlan(BaseModel):
    """Record of a plan selection linking CandidatePlan to ResearchPlan."""
    id: str
    sessionId: str
    candidateId: str
    researchPlanId: str
    createdAt: datetime = Field(default_factory=datetime.utcnow)
